export const siteConfig = {
  name: "Preeti Manoj | Developer Portfolio",
  authorName: "Preeti Manoj",
  username: "preetimanoj",
  description:
    "Preeti Manoj's portfolio",
  url: "https://preetimanoj.vercel.app",
  links: {
    twitter: "https://x.com/preetimanoj",
    github: "https://github.com/preetimanoj",
  },
  ogImage: "https://preetimanoj.vercel.app/preeti-img.jpg",
  iconIco:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357384/assets/naman-favicon.ico",
  logoIcon:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357294/assets/naman-logo.png",
  keywords: [
    "Preeti Manoj",
    "Full Stack Developer",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
